name: 'Update latest Kimai version'

on:
  repository_dispatch:
    types: [kimai_release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Update kimai version in _config.yml"
        run: scripts/update-version-number.sh "${{ github.event.client_payload.kimai_version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: update kimai_2_version to ${{ github.event.client_payload.kimai_version }}"
          title: "docs: update kimai_2_version to ${{ github.event.client_payload.kimai_version }}"
          branch: "docs/update-kimai-to-${{ github.event.client_payload.kimai_version }}"
